const STATE_NAMES = {
  AP: "Andhra Pradesh",
  AR: "Arunachal Pradesh",
  AS: "Assam",
  BR: "Bihar",
  CT: "Chhattisgarh",
  GA: "Goa",
  GJ: "Gujarat",
  HR: "Haryana",
  HP: "Himachal Pradesh",
  JH: "Jharkhand",
  KA: "Karnataka",
  KL: "Kerala",
  MP: "Madhya Pradesh",
  MH: "Maharashtra",
  MN: "Manipur",
  ML: "Meghalaya",
  MZ: "Mizoram",
  NL: "Nagaland",
  OR: "Odisha",
  PB: "Punjab",
  RJ: "Rajasthan",
  SK: "Sikkim",
  TN: "Tamil Nadu",
  TG: "Telangana",
  TR: "Tripura",
  UT: "Uttarakhand",
  UP: "Uttar Pradesh",
  WB: "West Bengal",
  AN: "Andaman and Nicobar Islands",
  CH: "Chandigarh",
  DN: "Dadra and Nagar Haveli and Daman and Diu",
  DL: "Delhi",
  JK: "Jammu and Kashmir",
  LA: "Ladakh",
  LD: "Lakshadweep",
  PY: "Puducherry",
  TT: "India",
  ["UNASSIGNED_STATE_CODE"]: "Unassigned",
};

/**
 * STATE_CODES: {
      "andhra ppradesh":"AP",
      "arunachal pradesh": "AR",
      assam: "AS",
      bihar: BR,
      chhattisgarh: CT,
      goa: GA,
      gujarat: GJ,
      haryana: HR,
      "himachal pradesh": HP,
      jharkhand: JH,
      karnataka: KA,
      kerala: KL,
      "madhya pradesh": MP,
      maharashtra: MH,
      manipur: MN,
      meghalaya: ML,
      mizoram: MZ,
      nagaland: NL,
      odisha: OR,
      punjab: PB,
      rajasthan: RJ,
      sikkim: SK,
      "tamil nadu": TN,
      telangana: TG,
      tripura: TR,
      uttarakhand: UT,
      "uttar pradesh": UP,
      "west bengal": WB,
      "andaman and nicobar islands": AN,
      chandigarh: CH,
      "dadra and nagar haveli and daman and diu": DN,
      delhi: DL,
      "jammu and kashmir": JK,
      ladakh: LA,
      lakshadweep: LD,
      puducherry: PY,
      india: TT,
      unassigned: ["UNASSIGNED_STATE_CODE"],
    }
 */

const JOKE_CATEGORIES = [
  "Any",
  "Dark",
  "Misc",
  "Spooky",
  "Christmas",
  "Programming",
  "Pun",
];

module.exports = { STATE_NAMES, JOKE_CATEGORIES };
